#!/usr/bin/env bash
export LANG=en_US.UTF-8
export LANGUAGE=en_US:en
export LC_ALL=en_US.UTF-8

# Ejecutar el comando de Ansible
ansible-playbook -i localhost  local.yml -t dotfiles --ask-become-pass --ask-vault-pass
