- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "fq211776@alumno.udb.edu.sv"
  tags:
  - git-personal
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "FQ211776"
  tags:
  - git-personal
