---
- name: Asegurar que existen los directorios de GPG
  file:
    path: "{{ ansible_env.HOME }}/.gnupg/{{ item | dirname }}"
    state: directory
    mode: '0700'
  loop: "{{ gpg_files }}"

- name: Copiar y desencriptar archivos GPG
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME }}/ansible/.gnupg/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.gnupg/{{ item }}"
    mode: '0600'
    decrypt: yes
    remote_src: yes  # Añade esta línea si los archivos están en el host remoto
  loop: "{{ gpg_files }}"

- name: Establecer permisos correctos en el directorio .gnupg
  file:
    path: "{{ ansible_env.HOME }}/.gnupg"
    mode: '0700'
    recurse: yes
